version: "3.8"
services:
  server:
    build: ./server
    ports:
      - "5000:5000"
    depends_on:
      - client
    container_name: tic-server
  client:
    build: ./client
    ports:
      - "3000:3000"
    container_name: tic-client
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: postgres
      POSTGRES_DB: todo_database
    ports:
      - "5432:5432"
